Repository auth0/auth0-oidc-client-net, pull requests merged in 2019-09, with the labels that each got.

#85 Fixed Auth0Client to allow overriding of RedirectUri.
  nuget/Auth0.OidcClient.Android.nuspec
  nuget/Auth0.OidcClient.iOS.nuspec
  src/Auth0.OidcClient.Android/Auth0Client.cs
  src/Auth0.OidcClient.Android/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.iOS/Auth0Client.cs
  src/Auth0.OidcClient.iOS/Properties/AssemblyInfo.cs
Labels: blocked, small

#88 Add helpful callback logger to debug
  src/Auth0.OidcClient.Core/Auth0ClientBase.cs
  src/Auth0.OidcClient.Core/Auth0ClientOptions.cs
Labels: small

#89 Prepare 2.4.2 release
  nuget/Auth0.OidcClient.Android.nuspec
  nuget/Auth0.OidcClient.Core.nuspec
  nuget/Auth0.OidcClient.UWP.nuspec
  nuget/Auth0.OidcClient.WPF.nuspec
  nuget/Auth0.OidcClient.WinForms.nuspec
  nuget/Auth0.OidcClient.iOS.nuspec
  src/Auth0.OidcClient.Android/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.Core/Auth0.OidcClient.Core.csproj
  src/Auth0.OidcClient.UWP/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.WPF/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.WinForms/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.iOS/Properties/AssemblyInfo.cs
Labels: small

#94 Rework Azure Pipeline so that it can compile iOS 13 SDK
  azure-pipelines.yml
Labels: tiny

#96 Update dependencies
  src/Auth0.OidcClient.Android/Auth0.OidcClient.Android.csproj
  src/Auth0.OidcClient.Core/Auth0.OidcClient.Core.csproj
  src/Auth0.OidcClient.UWP/project.json
  src/Auth0.OidcClient.WPF/Auth0.OidcClient.WPF.csproj
  src/Auth0.OidcClient.WinForms/Auth0.OidcClient.WinForms.csproj
  src/Auth0.OidcClient.iOS/Auth0.OidcClient.iOS.csproj
  test/Android/Android.csproj
  test/UWP/project.json
  test/WPF/WPF.csproj
  test/WinForms/WinForms.csproj
  test/iOS/iOS.csproj
Labels: tiny

#93 Set PresentationAnchor on iOS13 ASWebAuthenticationSession browser
  src/Auth0.OidcClient.iOS/ASWebAuthenticationSessionBrowser.cs
Labels: tiny

#95 Fix missing XML documentation
  src/Auth0.OidcClient.Android/ActivityMediator.cs
  src/Auth0.OidcClient.Android/AndroidBrowserBase.cs
  src/Auth0.OidcClient.Android/Auth0ClientActivity.cs
  src/Auth0.OidcClient.Android/AutoSelectBrowser.cs
  src/Auth0.OidcClient.Android/ChromeCustomTabsBrowser.cs
  src/Auth0.OidcClient.Android/PlatformWebView.cs
  src/Auth0.OidcClient.Android/Resources/Resource.Designer.cs
  src/Auth0.OidcClient.Android/SystemBrowser.cs
  src/Auth0.OidcClient.Core/Auth0ClientOptions.cs
  src/Auth0.OidcClient.Core/IAuth0Client.cs
  src/Auth0.OidcClient.UWP/PlatformWebView.cs
  src/Auth0.OidcClient.UWP/WebAuthenticationBrokerBrowser.cs
  src/Auth0.OidcClient.WPF/PlatformWebView.cs
  src/Auth0.OidcClient.WPF/WebBrowserBrowser.cs
  src/Auth0.OidcClient.WinForms/PlatformWebView.cs
  src/Auth0.OidcClient.WinForms/WebBrowserBrowser.cs
  src/Auth0.OidcClient.iOS/ActivityMediator.cs
  src/Auth0.OidcClient.iOS/AutoSelectBrowser.cs
  src/Auth0.OidcClient.iOS/PlatformWebView.cs
  src/Auth0.OidcClient.iOS/SFAuthenticationSessionBrowser.cs
  src/Auth0.OidcClient.iOS/SFSafariViewControllerBrowser.cs
  src/Auth0.OidcClient.iOS/iOSBrowserBase.cs
Labels: small

#97 Prepare 2.4.3
  nuget/Auth0.OidcClient.Android.nuspec
  nuget/Auth0.OidcClient.Core.nuspec
  nuget/Auth0.OidcClient.UWP.nuspec
  nuget/Auth0.OidcClient.WPF.nuspec
  nuget/Auth0.OidcClient.WinForms.nuspec
  nuget/Auth0.OidcClient.iOS.nuspec
  src/Auth0.OidcClient.Android/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.Core/Auth0.OidcClient.Core.csproj
  src/Auth0.OidcClient.UWP/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.WPF/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.WinForms/Properties/AssemblyInfo.cs
  src/Auth0.OidcClient.iOS/Properties/AssemblyInfo.cs
Labels: small

#98 More missing xml docs
  src/Auth0.OidcClient.Android/AndroidBrowserBase.cs
  src/Auth0.OidcClient.Android/AutoSelectBrowser.cs
  src/Auth0.OidcClient.Android/SystemBrowser.cs
  src/Auth0.OidcClient.iOS/ASWebAuthenticationSessionBrowser.cs
  test/Android/Resources/Resource.Designer.cs
Labels: tiny
